$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$parts = @(
    'parts/00-constants.glsl',
    'parts/10-hair.glsl',
    'parts/20-face-sdf.glsl',
    'parts/30-body-clothing.glsl',
    'parts/40-raymarch.glsl',
    'parts/50-lighting.glsl',
    'parts/60-main-image.glsl'
)

$output = Join-Path $root 'selfie_split.glsl'
$source = New-Object System.Text.StringBuilder

[void]$source.AppendLine('// Generated by build.ps1. Edit files in parts/, not this file.')
[void]$source.AppendLine()

foreach ($part in $parts) {
    $path = Join-Path $root $part

    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        throw "Required shader part is missing: $part"
    }

    [void]$source.AppendLine("// BEGIN $part")
    [void]$source.AppendLine([System.IO.File]::ReadAllText($path))
    [void]$source.AppendLine("// END $part")
    [void]$source.AppendLine()
}

$utf8WithoutBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($output, $source.ToString(), $utf8WithoutBom)

Write-Output "Built $output"